fix

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,76 +1,75 @@
 version: 2.1
 
 commands:
-  install_awscli:
-    description: Install AWS CLI v2
-    steps:
-      - run: 
-          name: Install AWS CLI v2
-          command: | 
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
-
-  install_ansible:
-    description: Install Ansible
-    steps:
-      - run: 
-          name: Install Ansible
-          command: | 
-            pip install ansible
-  
-  install_nodejs:
-    description: Install nodejs 13.8
+  install_aws_cli:
     steps:
       - run:
-          name: Install nodejs 13.8
-          command: | 
-            wget https://nodejs.org/download/release/v13.8.0/node-v13.8.0-linux-x64.tar.gz
-            tar xvzf node-v13.8.0-linux-x64.tar.gz
-            sudo cp -r node-v13.8.0-linux-x64/{bin,include,lib,share} /usr/
-            # sudo cp -r node-v13.8.0-linux-x64/include /usr/
-            # sudo cp -r node-v13.8.0-linux-x64/lib /usr/
-            # sudo cp -r node-v13.8.0-linux-x64/share /usr/              
+          name: Intall AWSCLI v2
+          command: |
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install  
+  install_ansible_ubuntu:
+    steps:
+      - run:
+          name: Intall ansible 
+          command: |
+            sudo apt update -y
+            sudo apt install ansible -y
+    
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
-      Workflow_ID:
-        type: string
-        default: ${CIRCLE_WORKFLOW_ID:0:7}
+      # Add parameter here
+      WORKFLOW_ID:
+        type: string 
+        default: ${CIRCLE_WORKFLOW_ID:0:7} # first 8 char of workflow id 
     steps:
-      - run: 
+      - run:
           name: Destroy environments
           when: on_fail
           command: |
-            aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.Workflow_ID >>
-            aws s3 rm s3://udapeople-<<parameters.Workflow_ID>> --recursive
-            aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.Workflow_ID >>
-
+            # Your code here
+            aws s3 rm s3://udapeople-<<parameters.WORKFLOW_ID>> --recursive
+            aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.WORKFLOW_ID >>
+            aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.WORKFLOW_ID >>
+         
+  install_nodejs13:
+    steps:
+      - run:
+          name: install nodejs 13
+          command: |
+            curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash - &&\
+            sudo apt-get install -y nodejs
   revert-migrations:
-    description: Revert the last migration if successfully run in the current workflow.
+    description: Revert the last migration
     parameters:
-      Workflow_ID:
+      workflow_id:
         type: string
-        default: ${CIRCLE_WORKFLOW_ID:0:7}    
+        default: ${CIRCLE_WORKFLOW_ID:0:7} # first 8 char of workflow id 
     steps:
       - run:
           name: Revert migrations
           when: on_fail
-          command: | 
-            SUCCESS = $(curl --insecure https://kvdb.io/WVeqKcg8v5ry767ySYYFmk/migration_<< parameters.Workflow_ID >>)
-            if(( $SUCCESS==1 )); 
+          command: |
+            # SUCCESS=$(curl -H "token: e52b52de-ee26-41a5-86e8-e8dcc3d995a5" --request GET https://api.memstash.io/values/migration_<< parameters.workflow_id >>)
+            SUCCESS=$(curl --insecure  https://kvdb.io/${KVDB_BUCKET}/migration_<< parameters.workflow_id >>)
+            # Logic for reverting the database state
+            if (( $SUCCESS == 1 ));
             then
-              cd ~/project/backend
-              npm install
-              npm run migration:revert
+                cd ~/project/backend
+                npm install
+                npm run migration:revert
             fi
-            
 jobs:
   build-frontend:
     docker:
-      - image: cimg/node:13.8.0
+      - image: circleci/node:13.8.0
     steps:
       - checkout
+      - run:
+          command: |
+            pwd
       - restore_cache:
           keys: [frontend-build]
       - run:
@@ -82,10 +81,12 @@ jobs:
       - save_cache:
           paths: [frontend/node_modules]
           key: frontend-build
+      - send_slack
+
 
   build-backend:
     docker:
-      - image: cimg/node:13.8.0
+      - image: circleci/node:13.8.0
     steps:
       - checkout
       - restore_cache:
@@ -99,188 +100,234 @@ jobs:
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
+      - send_slack
+
 
   test-frontend:
     docker:
-      - image: cimg/node:13.8.0
+      # Docker image here
+      - image: circleci/node:13.8.0
     steps:
+      # Checkout code from git
       - checkout
+      # Restore from cache
       - restore_cache:
           keys: [frontend-build]
+      # Your job code here
       - run:
-          name: Front-end unit test
+          name: test front-end
           command: |
             cd frontend
             npm install
-            npm test
-
+            npm run test
+      - send_slack
                 
   test-backend:
     docker:
-      - image: cimg/node:13.8.0
+      # Docker image here
+      - image: circleci/node:13.8.0
     steps:
       - checkout
+      # Restore from cache
       - restore_cache:
           keys: [backend-build]
+      # Your job code here
       - run:
-          name: Back-end unit test
+          name: test front-end
           command: |
             cd backend
             npm install
-            npm test
-
+            npm run test
+      - send_slack
             
   scan-frontend:
     docker:
-      - image: cimg/node:13.8.0
+      # Docker image here
+      - image: circleci/node:13.8.0
     steps:
       - checkout
+      # Restore from cache
       - restore_cache:
           keys: [frontend-build]
+      # Your job code here
       - run:
-          name: Front-end scan
-          command: |
-            cd frontend
-            npm install
-            npm audit fix --force --audit-level=critical
-            npm audit --audit-level=critical
-
-  scan-backend:
-    docker:
-      - image: cimg/node:13.8.0
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [backend-build]
-      - run:
-          name: Back-end scan
+          name: test front-end
           command: |
             cd backend
             npm install
-            npm audit fix --force --audit-level=critical
-            npm audit fix --force --audit-level=critical
-            npm audit --audit-level=critical
+            npm audit fix --audit-level=critical --force
+            # If the "npm audit fix" command above could not fix all critical vulnerabilities, try “npm audit fix --force” again
+            # npm audit --audit-level=critical
+      - send_slack
+
+  scan-backend:
+    docker:
+      # Docker image here
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      # Restore from cache
+      - restore_cache:
+          keys: [backend-build]
+      # Your job code here
+      - run:
+          name: test backend
+          command: |
+            cd backend
+            npm install
+            npm audit fix --audit-level=critical --force
+            # If the "npm audit fix" command above could not fix all critical vulnerabilities, try “npm audit fix --force” again
+            # npm audit --audit-level=critical
+      - send_slack
+  notify_slack_on_success:
+    docker:
+      - image: 'cimg/base:stable'
+    steps:
+      - run: echo "test my app"
+      - slack/notify:
+          event: pass
+          template: success_tagged_deploy_1
 
   deploy-infrastructure:
     docker:
       - image: cimg/base:stable
     steps:
       - checkout
-      - install_awscli
+      - install_aws_cli 
       - run:
           name: Ensure back-end infrastructure exists
           command: |
             aws cloudformation deploy \
-              --template-file .circleci/files/backend.yml \
-              --tags project=udapeople \
-              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
-              
+            --template-file .circleci/files/backend.yml \
+            --tags project=udapeople \
+            --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
       - run:
           name: Ensure front-end infrastructure exist
           command: |
             aws cloudformation deploy \
-              --template-file .circleci/files/frontend.yml \
-              --tags project=udapeaple \
-              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"   
-              
+            --template-file .circleci/files/frontend.yml \
+            --tags project=udapeople \
+            --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
       - run:
           name: Add back-end ip to ansible inventory
           command: |
+            # Your code here
             BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-             --query 'Reservations[*].Instances[*].PublicIpAddress' \
-             --output text)
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --output text)
             echo $BACKEND_PUBLIC_IP >> .circleci/ansible/inventory.txt
             cat .circleci/ansible/inventory.txt
-            
       - persist_to_workspace:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-      # Here's where you will add some code to rollback on failure     
-      - destroy-environment 
+      # Here's where you will add some code to rollback on failure      
 
   configure-infrastructure:
     docker:
-      - image: python:3.9
+      # Docker image here that supports Ansible
+      - image: cimg/base:stable
     steps:
+      # Checkout code from git
       - checkout
-      - run: 
-          name: Install AWS CLI v2
-          command: | 
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            ./aws/install
-      - install_ansible
+      - install_aws_cli
+      - install_ansible_ubuntu
       - add_ssh_keys:
-          fingerprints: ["73:43:dc:32:eb:95:c4:dc:e4:2b:9b:8f:0d:65:0b:e0"]
+          fingerprints:
+            - "48:8e:2c:c4:5e:eb:e6:57:f4:2f:37:65:ae:f6:69:99"
+      # Add ssh keys with fingerprint
+      # attach workspace
       - attach_workspace:
           at: ~/
       - run:
+          name: Install dependencies
+          command: |
+            # Your code here
+            # exit 1
+            echo "hello world"
+      - run:
           name: Configure server
           command: |
-            cd .circleci/ansible
+            cd .circleci/ansible/
             cat inventory.txt
+            echo """
+            [defaults]
+            host_key_checking = false
+            """ > ~/.ansible.cfg
+            # export ANSIBLE_HOST_KEY_CHECKING=False
             ansible-playbook -i inventory.txt configure-server.yml
-      - destroy-environment 
+      - destroy-environment
+            # Your code here
+            # exit 1
       # Here's where you will add some code to rollback on failure      
 
   run-migrations:
     docker:
-    - image: cimg/node:13.8.0
+      # Docker image here that supports NodeJS
+      - image: circleci/node:13.8.0
     steps:
+      # Checkout code from git
       - checkout
-      - install_awscli
+      - install_aws_cli
       - run:
           name: Run migrations
           command: |
+            echo "hello world"
             cd backend
             npm install
             npm run migrations > migrations_dump.txt
+            cat migrations_dump.txt
       - run:
-          name: Send migration status to kvdb.io
-          command: |
-            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
-            then
-              curl https://kvdb.io/WVeqKcg8v5ry767ySYYFmk/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
-            fi
-      - destroy-environment       
+          name: Send migration status to kvdb.io OR memstash.io
+          command: |   
+              if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+              then
+                  curl https://kvdb.io/WVeqKcg8v5ry767ySYYFmk/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+              fi
+      - destroy-environment
       - revert-migrations
+     # Here's where you will add some code to rollback on failure      
 
   deploy-frontend:
     docker:
+      # Docker image here that supports AWS CLI
       - image: cimg/base:stable
     steps:
+      # Checkout code from git
       - checkout
-      - install_awscli
-      - install_nodejs
-      - run:
-          name: Install dependencies
-          command: |
-            cd frontend
-            npm install
+      - install_ansible_ubuntu
+      - install_aws_cli
+      - install_nodejs13
+      - restore_cache:
+          keys: [frontend-build]
+      - attach_workspace:
+          at: ~/
       - run:
           name: Get backend url
           command: |
-            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-             --query 'Reservations[*].Instances[*].PublicIpAddress' \
-             --output text)
-
-            export API_URL="http://${BACKEND_PUBLIC_IP}:3030" >> frontend.env
+            export BACKEND_IP=$(aws ec2 describe-instances \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "API_URL = ${API_URL}"
+            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
             cat frontend/.env
       - run:
           name: Deploy frontend objects
           command: |
+            # your code here
             cd frontend
+            npm install
             npm run build
+            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-      # Here's where you will add some code to rollback on failure      
+      # Here's where you will add some code to rollback on failure
       - destroy-environment
-      - revert-migrations            
-
+      - revert-migrations
 #   deploy-backend:
 #     docker:
 #       # Docker image here that supports Ansible
